image: maven:3-jdk-11

stages:
  - compile-job
  - test-job

compile-job:
  stage: compile
  script:
    - mvn install -B
    - mvn compile

test-job:
  stage: test
  script:
    - mvn test


clean-job:
  stage: clean

