image: maven:3-jdk-11

stages:
  - compile
  - test-frontend
  - test-backend
  - clean

compile-job:
  stage: compile
  script:
    - make
    - mvn compile

test-syntax-job:
  stage: test-frontend
  script:
    - make
    - mvn -Dtest=FrontEndCompilerTest#runSyntaxErrorTests test
    
test-semantics-job:
  stage: test-frontend
  script:
    - make
    - mvn -Dtest=FrontEndCompilerTest#runSemanticErrorTests test


test-valid-job:
  stage: test-frontend
  script:
    - make
    - mvn -Dtest=FrontEndCompilerTest#runValidTests test
    
test-backend-job
  stage: test-backend
  script:
    - make
    - mvn -Dtest=BackEndCompilerTest test             

clean-job:
  stage: clean
  script:
    - make clean
