image: maven:3-jdk-11

stages:
  - compile
  - test
  - clean

compile-job:
  stage: compile
  script:
    - make
    - mvn compile

test-job:
  stage: test
  script:
    - make
    - mvn test

clean-job:
  stage: clean
  script:
    - make clean