image: maven:3-jdk-11

stages:
  - compile
  - test

compile-job:
  stage: compile
  script:
    - make
    - mvn install -B
    - mvn compile

test-job:
  stage: test
  script:
    - make
    - mvn test