image: gcc

stages:
  - precompile
  - compile
  - test
  - clean

precompile-job:
  stage: precompile
  script:
    - apt-get update && apt-get -y install make

compile-job:
  stage: compile
  script:
    - make

test-job:
  stage: test
  script:
    - echo "All tests pass!"

clean-job:
  stage: clean
  script:
    - make clean
