#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

puts "TODO: setup this script to call your WACC compiler"
java -cp bin:lib/antlr-4.9.1-complete.jar src/Compiler.java src/tests/invalid/syntaxErr/array/arrayExpr.wacc
